FROM golang:1.21.1

WORKDIR $GOPATH/src/chubby/
COPY . .

# Dependencies
RUN go get -d -v ./...

# Build executable
RUN go build -o chubby/leader_election_client1 chubby/cmd/leader_election.go

# Run simple_client exec
CMD ["chubby/leader_election_client1"]
