FROM golang:1.21.1

WORKDIR $GOPATH/src/chubby/
COPY . .

# Dependencies
RUN go get -d -v ./...

# Build executable
RUN go build -o bin/simple_client chubby/cmd/simple_client.go

# Run simple_client exec
CMD ["bin/simple_client"]
