FROM golang:1.21.1

WORKDIR $GOPATH/src/chubby/
COPY . .

# Dependencies
RUN go get -d -v ./...

# Build executable
RUN go build -o bin/chubby chubby/cmd/main.go

# Run chubby exec
CMD ["bin/chubby", "-id", "node3", "-listen", "172.20.128.3:5379", "-raftbind", "172.20.128.3:15379", "-join", "172.20.128.1:5379"]